# Generated by Django 4.0.2 on 2022-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='marked_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='store/images/'),
        ),
    ]
