# Generated by Django 4.0.2 on 2022-04-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_products_price_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='address',
            field=models.TextField(),
        ),
    ]
