# Generated by Django 4.0.2 on 2022-05-08 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_price_alter_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('time_slot', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
