# Generated by Django 4.0.2 on 2022-05-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_producttracker_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Unavailable')], default='1', max_length=100),
        ),
    ]
