# Generated by Django 4.0.2 on 2022-05-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_products_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsSellerFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_selling_quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('1', 'Available'), ('2', 'Unavailable')], default='1', max_length=100)),
                ('seller_name', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer_profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_state', models.CharField(choices=[('1', 'Bihar'), ('2', 'Delhi'), ('3', 'jharkhand'), ('4', 'UttarPradesh')], default='1', max_length=100)),
                ('marked_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('cost_price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
    ]
