# Generated by Django 4.0.2 on 2022-05-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productssellerfarmer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productssellerfarmer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
