# Generated by Django 4.0.2 on 2022-05-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_productssellerfarmer_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productssellerfarmer',
            old_name='customer',
            new_name='phone',
        ),
    ]
