# Generated by Django 4.0.2 on 2022-05-22 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_productsseller_seller_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsseller',
            unique_together={('product', 'seller_state')},
        ),
    ]
