# Generated by Django 4.0.2 on 2022-05-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_productsseller_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['status']},
        ),
    ]
