# Generated by Django 4.0.2 on 2022-05-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-status']},
        ),
    ]
