# Generated by Django 4.0.2 on 2022-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_products_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.TextField(default='Fresh and Nutritious with good packaging', max_length=500),
        ),
    ]
